# Master password is generated by Terraform BEFORE the DB instance is
# created, so there is never a window where the instance exists with a
# known/guessable placeholder password (this closes what the manual
# walkthrough left as GAP-1 — see README "Known gaps").
resource "random_password" "db_master_password" {
  length           = 24
  special          = false # matches --exclude-punctuation in the manual walkthrough
  override_special = ""
}

resource "aws_db_subnet_group" "this" {
  name       = "${var.project_name}-dbsubnet"
  subnet_ids = local.selected_subnet_ids

  tags = {
    Name = "${var.project_name}-dbsubnet"
  }
}

resource "aws_db_instance" "this" {
  identifier     = "${var.project_name}-mysql"
  engine         = "mysql"
  instance_class = var.db_instance_class

  allocated_storage = var.db_allocated_storage

  db_name  = var.db_name
  username = var.db_master_username
  password = random_password.db_master_password.result

  db_subnet_group_name  = aws_db_subnet_group.this.name
  vpc_security_group_ids = [aws_security_group.rds_sg.id]

  publicly_accessible = false

  # GAP-4 (tracked): 0 = no automated backups. Fine for a disposable lab
  # instance, wrong for anything holding real audit data. See README.
  backup_retention_period = var.db_backup_retention_period

  skip_final_snapshot = true
  apply_immediately    = true

  tags = {
    Name = "${var.project_name}-mysql"
  }
}
